### ISSUE TITLE
Implement Prezzemolo BFS in the CCXT pair converter

### ISSUE THREAD

**Issue by macanudo527** [eprbell/dali-rp2#124]
I'm going to try to work this in along with some other minor improvements including lazy load.

I'll need to check to make sure the same named vertex hasn't been added yet. Should I add that to the `_validate_vertex` function ([here](https://github.com/eprbell/prezzemolo/blob/a7909ad406153ba00da7a88f2a9ee8dbfd486142/src/prezzemolo/graph.py#L30)) or keep it in CCXT?

I'll also have to implement weights, which it looks like `prezzemolo` vertices accept but the search doesn't implement it in the graph class.

**Comment by eprbell** [comment]
> I'm going to try to work this in along with some other minor improvements including lazy load.

Great! 

> I'll need to check to make sure the same named vertex hasn't been added yet. Should I add that to the `_validate_vertex` function ([here](https://github.com/eprbell/prezzemolo/blob/a7909ad406153ba00da7a88f2a9ee8dbfd486142/src/prezzemolo/graph.py#L30)) or keep it in CCXT?

If the vertex has been added already, is it an error condition in the calling code? In other words what happens in your code if you find a duplicate vertex? 

> I'll also have to implement weights, which it looks like `prezzemolo` vertices accept but the search doesn't implement it in the graph class.

Oh interesting: what does your algorithm use weights for? If you need weights we need to implement Dijkstra (weighted shortest path): I would add a find_weighted_shortest_path method to Graph that implements Dijkstra.

**Comment by macanudo527** [comment]
> If the vertex has been added already, is it an error condition in the calling code? In other words what happens in your code if you find a duplicate vertex?

Basically the way vertices are added now is by market from multiple exchanges, so for example.

Exchange A has BTCUSD and BTCUSDT
Exchange B has BTCUSD and BTCUSDC

I need to add a BTC vertex with neighbors USD, USDT, USDC. I guess what I can do is have a `Dict` of vertices with keys of the name of the asset, add a vertex to it if the name doesn't exist. If it does exist, check if the quote asset is already a neighbor and if not retrieve that neighbor from the `Dict` and add the neighbor as I cycle through the markets. Then, add all the vertices to the graph.

Should I keep all that in CCXT?

> Oh interesting: what does your algorithm use weights for? If you need weights we need to implement Dijkstra (weighted shortest path): I would add a find_weighted_shortest_path method to Graph that implements Dijkstra.

I need to prioritize the main fiat currencies by trade volume (e.g. USD, EUR, JPY, etc...) over secondary ones (e.g. NGN, RUB, etc...) and to a lesser extent crypto asset pairs (e.g. BTC over ETH)

In the future, it might be good to give certain exchanges more weight for certain timeframes based on trade volume, but I think that will just be a simple `List`.

**Comment by eprbell** [comment]
Let's aim for keeping all of the graph logic into the `Graph` class, if possible, so that you don't have to write extra graph-specific code in the plugin. Let's see if we need to extend `Graph` or the current implementation is good enough. A few more questions/comments:
* If you add a vertex that was already added to the `Graph` class, the current implementation silently overwrites the old vertex with the new one without throwing error: is this good enough or would you prefer it to throw an exception?
* the neighbor check is already done by the `_validate_vertex()` method (see the for loop in it): do you need anything more than that as far as neighbor check is concerned?

As for the weighted shortest path, based on your description, it does look like we need Dijkstra.

**Comment by eprbell** [comment]
Let me also try to address your specific scenario precisely using the existing API (correct me if I'm missing something):
* discover that exchange A has BTCUSD and BTCUSDT
  * create vertexes BTC, USD and USDT
  * add 3 vertexes to a vertex set
  * btc.add_neighbor(usd)
  * btc.add_neighbor(usdt)
* discover that exchange B has BTCUSD and BTCUSDC
  * check what's already in the vertex set and create missing vertex USDC
  * add new vertexes to set (which results in only USDC being added)
  * get btc from vertex set and then btc.add_neighbor(usd), which returns ValueError because usd was already added (if you want we can add a `has_neighbor()` method to Vertex)
  * btc.add_neighbor(usdc)
* at this point we're ready to build the graph: transform vertex_set into a list and pass it to Graph's constructor.

Does this work?

**Comment by macanudo527** [comment]
> Does this work?

This pseudo code is what I'm looking for. I think we should add the `has_neighbor()`. That seems like a simple addition that can make it clearer.

Of course, to make this cleaner for CCXT it would be nice if we had some kind of `add_neighbor_to_existing_vertex_by_name()` function where I can simply call the following:
```
if vertex in graph.vertexes:
    graph.add_neighbor_to_existing_vertex_by_name("BTC", "USDC", self._ASSETS_TO_WEIGHT.get("USDC", 0.0))
else:
   v1 = new Vertex(name="BTC")
   v1.add_neighbor("USDC", _ASSETS_TO_WEIGHT.get("USDC", 0.0))
   graph.add_vertex(v1)
```
And it performs those checks internally. Something like:
```
def add_neighbor_to_existing_vertex_by_name(self, vertex_name, neighbor_name, weight = 0.0):
    vertex = self.__vertexes_by_name[vertex_name]
    neighbor = self.__vertexes_by_name[neighbor_name]
    if not vertex.has_neighbor(neighbor):
        vertex.add_neighbor(neighbor, weight)
```

Then, I can just call that function as I loop through the markets. 

P.S. I implemented Dijkstra. Let me know what you think. I ran all tests before submitting.

**Comment by eprbell** [comment]
+1 on adding `has_neighbor()`. I'm not sure about adding `add_neighbor_to_existing_vertex_by_name` to the Graph class. Wouldn't it be simpler to just do this?
```
# initialization
name_2_vertex = {}
...
# in the pair discovery while loop
from_vertex = name_2_vertex.setdefault(from_coin, Vertex(from_coin))
if not from_vertex.has_neighbor(to_coin):
  from_vertex.add_neighbor(Vertex(to_coin))
...
# outside the pair discovery while loop
pair_graph = Graph([vertex for name, vertex in name_2_vertex])
```

**Comment by macanudo527** [comment]
This has been implemented.
