### ISSUE TITLE
Bitbank withdrawals rest API

### ISSUE THREAD

**Issue by topherbuckley** [eprbell/dali-rp2#163]
In the [config docs](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#bitbank-supplemental-section-csv) it states that the "Bitbank Supplemental Section (CSV)... only supports withdrawals, which are not covered by the REST API. " 

Looking at the [REST API docs](https://github.com/bitbankinc/bitbank-api-docs/blob/master/rest-api.md#fetch-withdrawal-history), it looks like this is not true (maybe they added this since the doc was made?). 

I've never touched any REST API stuff, but will do my best to figure it out unless someone on here stops me and shows me that I'm misunderstood something.

**Comment by topherbuckley** [comment]
Also just curious, in the `test` dir, it doesn't look like there is any test for the existing bitbank rest API. Did this just never get done, or is it hanging out somewhere on some branch?

**Comment by topherbuckley** [comment]
Just noting that there is also a section in the config docs that states:

>At this time, the Bitbank REST API only supports trades. To process deposits and withdrawals please use the [Bitbank Supplemental CSV plugin](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#bitbank-supplemental-section-csv).

As I'll need to submit a PR to clear both of these should I succeed at this.

**Comment by macanudo527** [comment]
It was [added in Feb](https://github.com/bitbankinc/bitbank-api-docs/commit/a64b852a97e8dd4c70dbbecfc8a633bfe3f33a08), so that is why I had to build the supplemental CSV. You will still have to use it since [CCXT hasn't implemented the changes](https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/bitbank.py) yet. 

> Also just curious, in the `test` dir, it doesn't look like there is any test for the existing bitbank rest API. Did this just never get done, or is it hanging out somewhere on some branch?

The Bitbank rest API is built with the `abstract_ccxt_input_plugin.py`, which is tested via the Binance.com plugin, which it is derived from. It was so thin I didn't think it needed extra testing. Once withdrawals/deposits are implemented we might have to revisit that though.

We will have to wait on CCXT before we can change anything. Of course, you are welcome to contribute to that project. :)

**Comment by macanudo527** [comment]
Can we close this for now?
