### ISSUE TITLE
Coinbase API Fatal Execption - No Output File Generated

### ISSUE THREAD

**Issue by heiden12** [eprbell/dali-rp2#34]
When running dali to generate my files for rp2 I am getting a fatal error and no output file is generated. The execption I am seeing is:

Internal error: fiat_in_with_fee > fiat_out_no_fee

This is when using the Coinbase API plugin.

**Comment by eprbell** [comment]
Thanks for reporting a bug. Could you share the one line from your debug logs that shows the JSON returned by Coinbase for this transaction? 

Be sure to remove personal information from the line: in particular timestamps and ids. If you want to remove/mangle amounts you can do it but that will probably make it harder to come up with a correct implementation (if you do that, be sure to preserve sign information);

Here's how to do it:
* prepend your dali command line with LOG_LEVEL=DEBUG
* after running dali in debug mode, cd to the log directory, open the latest log and look for the line of the culprit transaction (check in the Coinbase section of the log)

Also please paste the full stack trace.

**Comment by eprbell** [comment]
Actually, I found where the error occurs in the code. No need to generate the debug log: the transaction data included with the error contains all the information needed. If you could paste that here (after anonymizing it) I can take a look.

**Comment by heiden12** [comment]
Here is the transaction data:

plugin=Coinbase
  unique_id=[id]
  raw_data={"id": "xxx", "type": "trade", "status": "completed", "amount": {"amount": "0.803107", "currency": "XTZ"}, "native_amount": {"amount": "2.40", "currency": "USD"}, "description": null, "created_at": "2021-07-26T20:05:57Z", "updated_at": "2021-07-26T20:05:57Z", "resource": "transaction", "resource_path": "/v2/accounts/xxx/transactions/xxx", "instant_exchange": false, "trade": {"id": "xxx", "resource": "trade", "resource_path": "/v2/accounts/xxx/trades/xxx"}, "details": {"title": "Converted to Tezos", "subtitle": "Using AMP Wallet", "header": "Converted 0.803107 XTZ ($2.40)", "health": "positive", "payment_method_name": "AMP Wallet"}, "hide_native_amount": false}
  timestamp=2021-07-26 20:05:57 +0000
  asset=XTZ
  exchange=Coinbase
  holder=[name]
  transaction_type=Buy
  spot_price=2.988393825480290920138910506
  crypto_in=0.803107
  fiat_fee=0
  fiat_in_no_fee=2.40
  fiat_in_with_fee=2.40
  notes=None//OutTransaction:
  plugin=Coinbase
  unique_id=xxx
  raw_data={"id": "xxx", "type": "trade", "status": "completed", "amount": {"amount": "-33.79269765", "currency": "AMP"}, "native_amount": {"amount": "-2.37", "currency": "USD"}, "description": null, "created_at": "2021-07-26T20:05:57Z", "updated_at": "2021-07-26T20:05:57Z", "resource": "transaction", "resource_path": "/v2/accounts/xxx/transactions/xxx", "instant_exchange": false, "trade": {"id": "xxx", "resource": "trade", "resource_path": "/v2/accounts/xxx/trades/xxx"}, "details": {"title": "Converted from Amp", "subtitle": "Using AMP Wallet", "header": "Converted 33.79269765 AMP ($2.37)", "health": "positive", "payment_method_name": "AMP Wallet"}, "hide_native_amount": false}
  timestamp=2021-07-26 20:05:57 +0000
  asset=AMP
  exchange=Coinbase
  holder=[name]
  transaction_type=Sell
  spot_price=0.07013349524642049404422141480
  crypto_out_no_fee=33.79269765
  crypto_fee=0E+29
  crypto_out_with_fee=33.79269765
  fiat_out_no_fee=2.37
  fiat_fee=0
  notes=None

**Comment by eprbell** [comment]
Thanks for the details: will look at it tomorrow.

**Comment by eprbell** [comment]
This is an AMP -> XTZ conversion, correct? It seems to be another case where the Coinbase REST API returns imprecise/bad fiat numbers (for another example see: https://github.com/eprbell/dali-rp2/issues/20).

Coinbase represents this swap with two transactions: a sale AMP -> USD and a buy USD -> XTZ. However fiat amounts (`native_amount/amount`) reported by Coinbase for the two transactions are:
* AMP -> USD: -2.37
* USD -> XTZ: 2.40

This is clearly incorrect because it suggests the AMP sale was worth $2.37 but the XTZ buy was worth $2.40 (normally the sale native_amount should be >= than the buy native_amount). DaLI points out this internal inconsistency in the data returned by Coinbase by raising the exception you see. 

Given that Coinbase sometimes returns bad data, the DaLI Coinbase plugin has to be robust enough to handle the bad data and still return reasonable results. So I changed the code to issue a warning (instead of an exception) when this situation is detected and use a zero fee (rather than a negative fee of $-0.03, which wouldn't make sense).

Please update DaLI to the latest version and let me know if the change fixes the issue. Thanks for reporting this!

**Comment by heiden12** [comment]
Do you push the fixes to the pip package? If not I can start a new project and pull down the source from github to test.

**Comment by eprbell** [comment]
Yes, the fix should be in v0.4.7 (available on pypi).

**Comment by heiden12** [comment]
I confirmed the new version is correctly generating output files.
