### ISSUE TITLE
Question/Proposal Non USD Base pairs.

### ISSUE THREAD

**Issue by jamesbaber1** [eprbell/dali-rp2#7]
Hello! First a wanted to say thanks for all your work on rp2. I have found it very useful. 

Actually over the past few weeks I have been writing my own tool for compiling data into the input format that RP2 takes. Then I saw this, and that youve already started working on this. So I thought I would reach out and at least let you know what I am working on.

So far it looks like you have been targeting US exchanges, however if your a US tax payer, trading on non US CEXs and DEXs can make getting the correct input challenging, since there is a bit of missing data that needs to be reconstructed with historical price data.   

Here is at least what my tool does, and I would like to see how you think this could fit into dali-rp2. This is still a WIP and I have 3 exchanges working now, but still have some more work to do before it is shareable.  The working name of it was "RP2 Compiler". Here is an section from my README.

**Comment by jamesbaber1** [comment]
## How does it work?
RP2 Compiler solves the challenges around computing the fair market value of trades and fees where the quote currency is not your country's fiat currency. This is
accomplished by matching historical data of various pairs down to the same minute that the trade took place. Take a look at this example of a trade on
`kucoin`.

![overview](https://user-images.githubusercontent.com/31859220/159135799-7d6acc75-e981-4204-9404-16f28a5b6c2d.svg)

| tradeCreatedAt | orderId | symbol | side | price | size | funds | fee | liquidity | feeCurrency | orderType |
|----------------|---------|--------|------|-------|------|-------|-----|-----------|-------------|-----------|
| 2021-09-02 03:38:24|612fd6b047d1a90544e0ccb2|LTC-BTC|sell|0.003709|10.331802|0.038320653618|0.000038320653618|taker|BTC|market|

This transaction is naive of the fair market value in USD that was gained after selling LTC, therefore RP2 compiler normalizes the table and
fills in the USDT amount of the transaction and fees using historical price data from the same minute of this transaction.

| Timestamp | Spot Price | Asset | Asset Amount | USDT Amount | USDT Fee | Transaction Type  | Closest Timestamp | Unique Id |
|-----------|------------|-------|--------------|-------------|----------|-------------------|-------------------|-----------|
|2021-09-02 03:38:24|184.13849760000002 | LTC | 10.331802 | 1902.4824977806754 | 1.9024824977806756 | sell | 2021-09-02 03:38:00 | 612fd6b047d1a90544e0ccb2 | 


## Supported Exchanges

RP2 Compiler integrates with exchanges in two ways. Downloaded UTF-8 encoded csv files from the exchange or via exchange API

| Logo | ID | Name | API | CSV |
|------|----|------|-----|-----|
| [![binance](https://user-images.githubusercontent.com/1294454/29604020-d5483cdc-87ee-11e7-94c7-d1a8d9169293.jpg)](https://www.binance.com)| binance| [Binance](https://www.binance.com) | no | yes |
| [![gateio](https://user-images.githubusercontent.com/1294454/31784029-0313c702-b509-11e7-9ccc-bc0da6a0e435.jpg)](https://www.gate.io)| gateio | [Gate.io](https://www.gate.io)| no | yes |
| [![huobi](https://user-images.githubusercontent.com/1294454/76137448-22748a80-604e-11ea-8069-6e389271911d.jpg)](https://www.huobi.com) | huobipro | [Huobi](https://www.huobi.com) | no | yes |
| [![kucoin](https://user-images.githubusercontent.com/51840849/87295558-132aaf80-c50e-11ea-9801-a2fb0c57c799.jpg)](https://www.kucoin.com) | kucoin | [KuCoin](https://www.kucoin.com) |yes | yes |

**Comment by jamesbaber1** [comment]
So far I have been leveraging [CCXT](https://github.com/ccxt/ccxt) for dowloading ohclv data and trade history, and patching up the missing USD prices of the assets.  Once I finish up my taxes, and finish up the support for at least the exchanges I used, Id be interested in contributing some.  

Like I said, I am most interested in helping get Non US based exchanges supported, and I know that historical data is needed to solve that. Also caching that process in steps becomes almost essential when there are tens of thousands of trades and the price data starts becoming dozens of GB. So I have a workable solution for caching and rebuilding a cache, but did want to eventually contribute back, in such a way that can fit with your design.

**Comment by eprbell** [comment]
Thanks for this thread and for starting a RP2 ecosystem project! Sounds like you have an interesting use case I hadn't thought about, since I have no experience with foreign exchanges. I'm not sure I understand fully the flow in the first picture. Could you clarify why you need three conversion steps (why not just LTC->BTC and BTC->USD)?

Regarding the issue of RP2 Compiler as a standalone vs DaLI integration, I think It would be great if you could bring your data loaders directly into DaLI as input plugins, because all DaLI loaders benefit from common infrastructure like the transaction resolver, ODS generator and transaction parameter checking: any new loader provides exponential benefits to the entire system and increases dramatically its usefulness to the final user. I'm guessing that if you already have code that reads from the exchanges and generates RP2-ready input, it should be relatively easy to convert it into DaLI data loader plugins. However, if you prefer, you can keep RP2 Compiler as an external project: in this case you could consider generating input to the [DaLI manual plugin](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#manual-section-csv). This would make it possible to feed data from RP2 compiler directly into DaLI, so that the data can be merged with data from other DaLI plugins (but this approach would be a bit more cumbersome for the final user compared to native plugins). 

I would also like to learn more about your caching solution: would you elaborate a bit on it?

BTW, thanks for pointing to CCXT: it looks great. I haven't used it for DaLI's Coinbase and Coinbase Pro plugin because I wanted to do a full proof-of-concept without external libraries, but, looking back, I'm wondering if that was a wise choice. Going forward it probably makes sense to implement CCXT plugins for all the exchanges it supports. I will add a link to it to all the open issues for data loader plugin implementation.

**Comment by eprbell** [comment]
One more question: where do you get historical prices from?

**Comment by jamesbaber1** [comment]
> clarify why you need three conversion steps (why not just LTC->BTC and BTC->USD)?

So in some cases only three steps would be necessary. But in the above case with kucoin there is no BTC/USD pair. However almost all foreign centralized exchanges have USDT pairs. Since all historical data is being pulled directly from the exchange usually I can only normalize the data to USDT amount using just the exchange API. So I didn't want to introduce another data source as an input, that the user may or may not have access to. But eventually as a finally step I could use any exchange(preferably one with a high daily volume) to go back through and convert the USDT/USD or USDT/EUR etc. as the final step.


> I would also like to learn more about your caching solution: would you elaborate a bit on it?

So basically there is just some incremental saving of files after they have been downloaded and normalized or read from raw csv and normalized. But the biggest need is for the price history cache, because even though I cache only 24h periods of 1m candles around a trade(just in case some minutes are missing so I can round to the nearest) it has still ended up being like 14GB for me.  I trade alot, and on alot of pairs, so I am probably more on the larger side, but if you say traded on 200 pairs in 2021 and cached all available 1m candles that ends up taking awhile.  Some times all that historical data isn't necessary especially if you stick to trading USDT and your exchange has good trade history data(not like binance) then most of the normalization doesnt need to make any kinda of REST call to an exchange api.  

![image](https://user-images.githubusercontent.com/31859220/159142496-624790eb-e82d-4b64-abdb-ff14bb9e46c3.png)

This is what it looks like. The rp2_data cache is really just to help me debug at the moment, but the others are kinda needed especially the price data.  I was going to make an option to blow away the normalized trades since that doesn't add to much time when re-computing, however fetching the ohlcv data that I need is taking about 7hrs for my use case currently. So some kinda of cache to pickup where you left off might be beneficial.



> One more question: where do you get historical prices from?

The historical data comes from the standardized [fetchOHLCV](https://docs.ccxt.com/en/latest/manual.html#ohlcv-structure) method in [CCXT](https://github.com/ccxt/ccxt) which also has a standardized [fetchMyTrades](https://docs.ccxt.com/en/latest/manual.html#personal-trades) on alot of exchanges. There are some caveats with some exchanges, but for the most part ccxt has help speed up cross exchange compatibility for alot of crypto apps. I was wondering if you would consider it?

**Comment by eprbell** [comment]
Thanks for the additional details. DaLI's [transaction_resolver](https://github.com/eprbell/dali-rp2/blob/main/src/dali/transaction_resolver.py) also uses historical price data, if it's not available in the native format (which doesn't happen very often): currently it uses Yahoo Finance historical prices, which only has daily min, max and little more, and therefore it's not very precise. So it would be great to switch to a solution like yours, which seems to have high-resolution data.

**Comment by jamesbaber1** [comment]
Ok cool, I'll at least wrap up my work so I can finish my tax return, and then might drop a link to the repo here in a week or so, so you can take a look. Then discuss it a little more and then I'll put together a PR

**Comment by macanudo527** [comment]
@jamesbaber1 

CCXT uses the Binance api to pull historical data, so I think it waits between calls in order to not hit the request weight limit. They do make all of the data available via the [Binance Public Data](https://github.com/binance/binance-public-data) repo. Data is uploaded daily, so it will be a day behind but should be okay for taxes.

There is also [1 minute forex data repo](https://github.com/philipperemy/FX-1-Minute-Data), too. It has a Python interface, but it is pretty simple and we could roll it into DaLi. You could combine the two and be able to quickly pull data and do currency conversions to any common currency. 

Maybe save the CSVs and check for their presence?

**Comment by eprbell** [comment]
@macanudo527, a few comments/updates on historical prices and caching and a question:
* recently I switched historical price fetching from Yahoo Finance (which had daily granularity) to Coinbase Pro (which has minute granularity): this occurs outside plugins in the transaction_resolver and it happens only if the `-s` switch is passed and if the spot price is unknown (e.g. in certain INTRA/MOVE transactions, etc.). See https://github.com/eprbell/dali-rp2/blob/main/src/dali/transaction_resolver.py#L133;
* @stevendavis has proposed a new configuration section to configure historic price providers (see issue #23): perhaps we could add Binance there as a historical price provider;
* @houqp added caching infrastructure to DaLI: this infrastructure is now used in various places, including historical price fetching, so there should be no need to save a CSV file (see https://github.com/eprbell/dali-rp2/blob/main/src/dali/transaction_resolver.py#L121 and https://github.com/eprbell/dali-rp2/blob/main/src/dali/transaction_resolver.py#L144)

However could you elaborate on why we would need the two dependencies you listed: would CCXT not be enough?

**Comment by macanudo527** [comment]
@eprbell I guess I was thinking that historical price resolution would work per exchange and there would not be a global solution since there could be discrepancies in prices. (I hadn't looked into the transaction resolver yet.)

For example, a whale could flash crash an exchange and you had a limit order in. You could buy the coin at a lower price at that exchange until the arbitrage bots caught up. Or if you were dealing with illiquid assets, there could be a spread on some exchanges. This can happen a lot when trading base pairs other than USD stable. Like if you were trading FLUXETH for example. 

If price resolution were per exchange it would be much faster to download the historical data off the repo than using the api since there are request limitations that would slow retrieval down significantly. 

Of course integrating it could be done later if the speed is too slow. It doesn't have to be done now. 

The forex data is for all major pairs of currency. Does coinbase pro have information on all the pairs? (E.g. EURGBP)

**Comment by macanudo527** [comment]
> As for performance concerns, I think the caching infrastructure should address most of them (it would be slow only the first time it runs).

Sounds good. 

> I hadn't thought that in the case of foreign exchanges (which need non-USD fiat) perhaps historical prices might be needed within the plugin as well, not just in the transaction resolver (however the caching infra will solve  performance concerns in this case too).

I know I'm a fringe use case but my on-ramp is JPY. So, I'll buy XLM (no stable coins in Japan) in JPY then send it to a global exchange and convert to USDT, which will eventually have to be converted into JPY in order to do taxes in Japan. 

The problem arises that the first purchase will be the 'real' price I bought the asset. But the conversion to USDT will be an approximation based on USDT's value in USD then converted to JPY. 

So the transaction resolver could convert the native fiat into the one that is needed. (I need USD for US taxes and JPY for Japan.)

I apologize for all this. I'm a fringe case and can definitely do my best to code this in myself. Just thought I would share the info. 

One thing that came to mind is we could just use coinmarketcap's API. It has a [conversion function](https://coinmarketcap.com/api/documentation/v1/#operation/getV2ToolsPriceconversion) that converts pretty much any coin to any major fiat currency. Users would need an API key, but the free plan has 10k calls a month for free. If the user uses those up you could fallback on Coinbase for US users and Binance for everyone else. 

Coinmarketcap lists thousands of coins from the bottom of the barrel up.

Coinbase Pro has [397 pairs](https://coinranking.com/exchange/qn5ZJmPFP+coinbase-pro/markets) listed while Binance has [1292 pairs](https://coinranking.com/exchange/-zdvbieRdZ+binance/markets) (according to that site, but actually when I pulled exchange info from them, it reported 1970+)

**Comment by jamesbaber1** [comment]
My main motivation for building a tool that downloads for RP2 was because, at least for my use case, sites like koinly.com for example only use coinmarketcap and coingecko data sources. While these do have alot of pairs they dont have everything, and where you really run unto problems, is with leverage tokens on various exchanges, which you can't derive solely from spot price because of how the NAV works on these pairs, so you need the exact history for these, on the exchange you bought it from. For example I had 62 pairs with missing historical data across 4 exchanges that koinly couldn't resolve.  I was able fetch down to the minute the spot price directly from the exchanges ohclv data, and then using the "matching method" pictured above to at least normalize the historical price to a coin that can easily be converted to fiat from a variety of data sources, I was able to resolve all of these on `binance`, `gateio`, `houbi` and `kucoin`, even when trading alts quoted against `BTC`, `ETH`, `BNB`, `HT`, `GT`, `KCS`.  

The reason I am pushing [ccxt](https://github.com/ccxt/ccxt) is it already has implementation for auth, rate limiting, and has some key generic methods like `[fetchOHLCV](https://docs.ccxt.com/en/latest/manual.html#ohlcv-structure)` and `[fetchMyTrades](https://docs.ccxt.com/en/latest/manual.html#personal-trades)` for 118 exchanges already and wont require us to re-invent the wheel.

Personally I think the source of truth for price history should always be the exchange you placed the order on. Like @macanudo527 mentioned prices can vary at points in time especially on low volume pairs on low volume exchanges, so when it comes to price data the most accurate price will be the historical price at the same minute on the same exchange that you made the purchase on.  However if that data is missing youll have to pull from other sources like coin gecko or coinmarketcap. So maybe it resolves in that order.

Ill can port over my ohlcv and trade downloader classes from my tool into a PR once I tie up some lose ends. I need to clean stuff up and document the code a bit. Hopefully wont be much longer

**Comment by eprbell** [comment]
@jamesbaber1, maybe the right approach is the one you started this thread with: have a separate tool that deals correctly with the currency pair problem and generates input for DaLI/RP2. When the tool you're building is ready I'll be sure to take a look. I'm still trying to understand fully the spec / use case, so I haven't formed a strong opinion yet on whether to build this functionality in DaLI or in an ecosystem project.

**Comment by macanudo527** [comment]
@eprbell I think you summarized it well.  One question about this:

> plugins (like the binance.com one) can use this new infrastructure to convert fiat pairs as needed

So, the idea is the plugin would convert the fiat transactions to the base fiat? For example, if I purchased assets with JPY and was doing US taxes it would convert to USD? I would think this logic would be in the transaction resolver and it would convert to the base fiat as it was processing all the transactions. That way, all transactions come out of the plugins in their native fiat currency first and then converted for each pull. I'll have to pull data once for US taxes, then again for Japan taxes using the same transactions just in a different base fiat.

**Comment by eprbell** [comment]
So I think we need to evaluate two approaches to this problem:
1. internal approach: all the logic is inside DaLI (as you and I discussed and as summarized in my previous post);
2. external approach: this is what @jamesbaber1 did and in his approach the non-usd pairs are handled in another project, which then feeds the normalized input to DaLI.

I'm still unsure what the best approach would be, but to begin with we can start experimenting with 1. And finally to answer your question: in case 1 I think you're right: fiat resolutions should occur in the transaction resolver, so that plugins can express fiat as JPY or other and don't have to worry about it. However the transaction resolver will need to know what fiat was used: we can probably add a per-transaction field to express that.

**Comment by eprbell** [comment]
I think has now been implemented for the most part. The new [pair converter plugin architecture](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#pair-converter-plugin-development) together with the [country plugin architecture](https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#country-plugin-development) enable support of the use case described in this issue. 

Here's how it all comes together:
* the country plugin can be used to define the "default fiat" (USD for US, JPY for Japan, etc.) for a given run;
* when creating transactions, data loader plugins can specify the `fiat_ticker` field to indicate the fiat a transaction's fiat fields are denominated in: if `fiat_ticker` is not used, the transaction's fiat fields are assumed to be denominated in the default fiat;
* the transaction resolver analyzes all transactions created by the data loaders: if it finds any that have `fiat_ticker` != default fiat, it uses the pair converters to convert fiat fields from `fiat_ticker` -> default fiat.

Note that:
* the user can specify any number of [pair converters in the .ini file](https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#pair-converter-plugin-sections). When DaLI (and specifically the transaction resolver) needs to query a price, it will ask the first pair converter indicated in the .ini file. If the price is unavailable it will move on to the second one, etc (so order matters in the .ini file). Currently we only have one pair converter plugin (Historic-Crypto) and we need to add more (CCXT and probably others).
* the pair converter plugins make use of DaLI's cache infrastructure so prices are only queried once, even across multiple runs.

If you have any questions or comments, let me know.

CC: @stevendavis and @macanudo527, who have been working on part of the above or on components adjacent to the above.

**Comment by macanudo527** [comment]
Does #53 resolve this?

**Comment by eprbell** [comment]
@macanudo527, I think your CCXT pair converter plugin with price routing (#53) and the rest of the currency conversion infra covers most of the features described here. Let's close this and if anything is missing or buggy we can open new, more granular issues.

**Comment by jamesbaber1** [comment]
Sounds good. Yea sorry guys for my lack of involvement. I plan on writing several CCXT plugins once @macanudo527 finishes up the abstract CCXT plugin.

**Comment by eprbell** [comment]
No apology needed! You started this discussion with a design and lots of good insight. Any future contributions you want to make will be happily received 🙂
